name: kid_need_pishrun_event_02
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.14
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable:
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  flutter_svg:

  flutter_spinkit: ^5.1.0
  just_audio: ^0.9.18
  just_audio_background:
  audio_session:
  audio_video_progress_bar: ^0.10.0

  syncfusion_flutter_sliders: ^19.4.43
  syncfusion_flutter_core: ^19.4.43+1
  intl: ^0.17.0
  persian_datetime_picker:
  shamsi_date:

  flutter_keyboard_visibility: ^5.1.1

  flutter_rating_bar: ^4.0.0

  vibration:

  url_launcher: ^6.0.8

  cupertino_icons: ^1.0.2

  super_enum: ^0.5.0

  pull_to_refresh: ^2.0.0
  package_info: ^2.0.2
  http: ^0.13.4
  dio: ^4.0.4
  url_strategy: ^0.2.0
  connectivity_plus: ^1.1.0
  share_plus: ^3.0.0
  device_info_plus: ^3.2.1
  permission_handler: ^8.3.0
  get_storage: ^2.0.3
  lottie: ^1.2.1
  flutter_native_splash: ^2.0.1+1
  flutter_markdown: ^0.6.9
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  super_enum_generator: ^0.6.0
  build_runner:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo_rectangle.png"

flutter:

  uses-material-design: true


  assets:
    - images/
    - images/ionic/
    - images/animations/


  fonts:
    - family: iranSans
      fonts:
        - asset: fonts/iran_sans_dn_fa_num_bold.ttf
          weight: 700
        - asset: fonts/iran_sans_dn_fa_num.ttf
        - asset: fonts/iran_sans_dn_fa_num_light.ttf
          weight: 300
    - family: dana
      fonts:
        - asset: fonts/dana_fa_num_bold.ttf
          weight: 700
        - asset: fonts/dana_fa_num_medium.ttf
        - asset: fonts/dana_fa_num_light.ttf
          weight: 300